### ISSUE TITLE
教务网站的网址发生了变更

### ISSUE THREAD

**Issue by MercatorProj** [linkedlist771/UCAS-AutoClassEvaluation#1]
教务网站的网址发生了变更：
原匹配规则： 
// @match        https://jwxk.ucas.ac.cn/evaluate*
应加上：
// @match    https://xkcts.ucas.ac.cn/evaluate*

**Comment by linkedlist771** [comment]
谢谢提醒已修改， 如有更好建议，欢迎提交PR。
